### ISSUE TITLE
Bind is always 0.0.0.0 regardless of specified address in listener

### ISSUE THREAD

**Issue by netixx** [bio-routing/bio-rd#450]
**Describe the bug**

**Steps to Reproduce**
in cmd/bio-rd/main.go, configure a bind IP for 
```
listenAddrsByVRF := map[string][]string{
		vrf.DefaultVRFName: {
			"10.0.0.1:179",
		},
	}
```

**Expected behavior**
The program should bind the socket on the provided IP address.

**Configuration used**
```
routing_options:
  autonomous_system: 111
  router_id: 10.0.0.1
policy_options:
  policy_statements:
    - name: "ACCEPT_ALL"
      terms:
        - name: "ACCEPT_ALL"
          then:
            accept: true
    - name: "REJECT_ALL"
      terms:
        - name: "REJECT_ALL"
          then:
            reject: true
protocols:
  bgp:
    groups:
      - name: "IXP RS Clients"
        local_address: 10.0.0.1
        #route_server_client: true
        passive: true
        neighbors:
          - peer_address: 10.0.0.2
            peer_as: 111
            import: ["ACCEPT_ALL"]
            export: ["REJECT_ALL"]
```
+ change bind address in code

**Additional context**
By modifying the code in net/tcp/listen.go the following way:
```
fmt.Println(laddr.IP)
    fmt.Println(ipv4AddrToArray(laddr.IP))
    if laddr.IP.To4() != nil {
        err = unix.Bind(fd, &unix.SockaddrInet4{
            Port: laddr.Port,
            Addr: ipv4AddrToArray(laddr.IP),
        })
    } else {
        err = unix.Bind(fd, &unix.SockaddrInet6{
            Port: laddr.Port,
            Addr: ipv6AddrToArray(laddr.IP),
        })
    }
```

I was able to produce the following output:
```
strace -e trace=network ./bio-rd
10.0.0.1
[0 0 0 0]
bind(13, {sa_family=AF_INET, sin_port=htons(2179), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
```

As you can see the bind call is 0.0.0.0 beccause ipv4AddrToArray returns [0 0 0 0].
